- package.json
Fixes: https://github.com/nodejs/amaro/issues/16
> fix: remove exports

- .github/workflows/ci.yml
- biome.json
- package.json
- test/index.test.js
- test/setup.mjs
- test/snapshots/index.test.js.snapshot
- test/snapshots/snapshot-config.js
Greetings, I added a test and tried to get more coverage
- Add test for stripping type annotations from functions
- Add test for stripping type annotations from classes
- Add test for stripping type annotations from interfaces
- Add test for stripping type annotations from type aliases
- Add test for stripping type annotations from generics
- Add test for stripping type annotations from arrow functions
- Add test for stripping type annotations from type assertions
Additionally, I have integrated node 22 snapshot testing as suggested. The snapshot tests have been normalized to handle line endings and formatting issues
> feat: add TypeScript type annotation tests with node 22 snapshots

- .github/workflows/update-swc.yml
#28 
This workflow runs every Monday at `00:00` UTC and can also be started manually.
It checks the latest SWC version on npm and compares it to the one contained in `package.json`.
Feel free to review each step that could be improved, this is the first time I've created such workflow. (It was interesting to learn how to do it even if you close it :+1: ).
I tested it on a private repo, here's the PR result:
> feat: add  `swc` update workflow

- .github/workflows/update-swc.yml
Fix https://github.com/nodejs/amaro/issues/28#issuecomment-2265909540
It's totally my fault for not checking that this create PR action didn't have the same behaviour as the one I first used.
I've also reworked the way it check if an update is needed, now the workflow skips all steps if no update is needed, inspired by https://github.com/nodejs/node/blob/main/.github/workflows/update-openssl.yml
PR result: 
If no update is required :
> fix: `update-swc` create pr and check swc update

- tools/build-wasm.js
I did not test this / not sure where to run it, please recheck
> chore(tools): fix command injection via __dirname in build process

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/update-swc.yml
- tsconfig.json
Fixes: https://github.com/nodejs/amaro/issues/33
> chore(tools): pin gh actions commit version

- .github/workflows/audit.yml
- deny.toml
- tools/Dockerfile
This should allow scanning on both rust and typescript
> code scanning

- package.json
If you want to rely on node’s test runner’s glob expansion the glob patterns should be enclosed in quotes. Otherwise the shell will do the glob expansion which can have different behaviors depending on the system. 
> The glob patterns should be enclosed in double quotes on the command line to prevent shell expansion, which can reduce portability across systems.
https://nodejs.org/docs/latest/api/test.html#running-tests-from-the-command-line
> chore(tools): enclose test glob patterns in quotes

- src/index.ts
- test/index.test.js
makes sure the input is a string, so we can remove this check from node core
> fix: enforce source code is a string

- src/transform.ts
- test/snapshots/transform.test.js.snapshot
- test/transform.test.js
cc @nodejs/typescript 
I also wonder which other options we should set by default during transformation
```typescript
interface TransformConfig {
/**
* @see https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax
*/
verbatimModuleSyntax?: boolean;
/**
* Native class properties support
*/
nativeClassProperties?: boolean;
importNotUsedAsValues?: "remove" | "preserve";
/**
* Don't create `export {}`.
* By default, strip creates `export {}` for modules to preserve module
* context.
* 
* @see https://github.com/swc-project/swc/issues/1698
*/
noEmptyExport?: boolean;
importExportAssignConfig?: "Classic" | "Preserve" | "NodeNext" | "EsNext";
/**
* Disables an optimization that inlines TS enum member values
* within the same module that assumes the enum member values
* are never modified.
* …
```
> chore: add correct defaults

- test/snapshots/transform.test.js.snapshot
Updating swc changed the output , appending `/*#__PURE__*/` to functions
> fix: regenerate tests after swc update

- .github/workflows/ci.yml
- .github/workflows/release.yml
- For release workflow, we use `.nvmrc`
- For CI, we use `22` and `23` for test
> chore(workflow): update node version

- test/index.test.js
- test/snapshots/transform.test.js.snapshot
- test/transform.test.js
Refs: https://github.com/nodejs/typescript/issues/17#issuecomment-2475709279
cc @robpalme
> test: check syntax is not polyfilled

- tools/build-wasm.js
Update to get latest wasm-builder container as a newer version of Rust is needed for the recent SWC update
A tweak was required to the build script in addition due to the Rust install being refactored in the container to support pulling in newer Rust versions
> chore: update to latest wasm-builder container

- test/fixtures/hello.js
- test/loader.test.js
Hi :blush: I was looking into tests code coverage and it seems that for non typescript files we're not ensuring that `nextLoad` is called, there:
https://github.com/nodejs/amaro/blob/2ebb06345322ed1fa938426aa9673b886ce12e6c/src/strip-loader.ts#L35 and there:
https://github.com/nodejs/amaro/blob/2ebb06345322ed1fa938426aa9673b886ce12e6c/src/transform-loader.ts#L43
This PR adds tests that checks that, but if You think that it is something that is not worth to test please let me know so I will close this PR.
Also wondering: is there any reason why test coverage for amaro is not configured here https://app.codecov.io/gh/nodejs? or it's just luck of time/resources?
> test: ensure loaders passes for non ts

- test/snapshots/transform.test.js.snapshot
- test/transform.test.js
Refs: https://github.com/nodejs/node/issues/56296
> test: add a test case for unusual charsets

- biome.json
- release-please-config.json
By default, release-please ignores `chore` categories in the change log ([ref](https://github.com/conventional-changelog/conventional-changelog/blob/8076d4666c2a3ea728b95bf1e4e78d4c7189b1dc/packages/conventional-changelog-conventionalcommits/writer-opts.js#L171)).
> chore: include chore in change logs

- biome.json
- esbuild.config.mjs
- src/errors.ts
- src/strip-loader.ts
- src/transform-loader.ts
- test/fixtures/invalid-syntax.ts
- test/loader.test.js
- tsconfig.json
I'd accept suggestion on how to better handle esbuild. It seems a bit messy 😫 
We need to wrap swc `transformSync` because it now throws an object.
> feat: wrap and rethrow swc errors

- test/index.test.js
Refs: https://github.com/swc-project/swc/issues/9883
@nodejs/typescript I'm pretty sure this syntax should be invalid and should throw a syntax error.
> test: swc allows invalid js syntax

- test/index.test.js
- test/snapshots/index.test.js.snapshot
@kdy1 I think we should support type stripping of empty namespaces because they are erasable and are supported by erasableSyntaxOnly
cc @nodejs/typescript 
Tests copied from https://github.com/bloomberg/ts-blank-space/pull/32
> test: check erasable namespaces are supported

- src/errors.ts
- test/loader.test.js
- test/snapshots/transform.test.js.snapshot
- test/transform.test.js
This change is more useful in Node.js core than in Amaro as an external loader. Unfortunately snippets are not working so that's blocking
> feat: build error snippet manually

- test/index.test.js
- test/snapshots/index.test.js.snapshot
This test ensures that `transformSync` can safely strip advanced TypeScript type-level constructs like:
- infer
- keyof
- typeof
All constructs are removed correctly using `mode: "strip-only"` and generate no runtime output, as expected.
Snapshot was generated using `NODE_TEST_UPDATE_SNAPSHOTS=1`.
No runtime behavior is affected. Test passed successfully under Node.js v24.0.0.
> test: add snapshot for advanced type-level constructs

- test/index.test.js
- test/snapshots/index.test.js.snapshot
This test ensures that `transformSync` can safely strip satisfies expressions.
The expression:
```
const user = {
name: "Alice",
age: 30,
} satisfies { name: string, age: number };
```
All constructs are removed correctly using mode: "strip-only", as expected.
A Snapshot was generated.
No runtime behavior is affected. 
Node.js v24.1.0
> test: add snapshot for satisfies expressions

- test/index.test.js
- test/snapshots/index.test.js.snapshot
This test ensures that `transformSync` preserves valid `import type` and `export type` declarations
```
import type { SomeType } from "./types";
export type { SomeType };
```
All constructs are removed correctly using mode: "strip-only", as expected. A Snapshot was generated.
Node.js v24.3.0
> test: add snapshot for import/export type declarations

- test/snapshots/transform.test.js.snapshot
- test/transform.test.js
This PR adds a test to prevent regressions on an already fixed issue, reported here: https://github.com/nodejs/node/issues/59737
> test: add snapshot for short-circuit assignments
